In [1]:
import torch
import numpy as np

# Creating tensors in PyTorch

In [9]:
a = [1, 2, 3]
t_a = torch.tensor(a)
print(t_a)

tensor([1, 2, 3])


In [10]:
b = np.arange(4, 7, dtype = np.int32)
t_b = torch.from_numpy(b)
print(t_b)

tensor([4, 5, 6], dtype=torch.int32)


In [14]:
# there are equivalent functions of np in torch
# np.ones --> torch.ones
t_ones = torch.ones(size = (2,3))
print(t_ones)

# they also have properties such as dtype and shape
print(t_ones.dtype)
print(t_ones.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32
torch.Size([2, 3])


In [21]:
# Both are equivalent ways to get random samples from U(0,1)
# but rand_tensor0 can be used to get samples from U(r1, r2) too

rand_tensor0 = torch.FloatTensor(2, 3).uniform_(0, 1)
print(rand_tensor0)

rand_tensor1 = torch.rand(2, 3)
print(rand_tensor1)

tensor([[0.1269, 0.8651, 0.0426],
        [0.3969, 0.0243, 0.1242]])
tensor([[0.5336, 0.2635, 0.9858],
        [0.5510, 0.5420, 0.9060]])


In [23]:
print(t_a)
print(t_a.dtype)
# change data type of a tensor
t_a_new = t_a.to(torch.float64)
print(t_a_new)
print(t_a_new.dtype)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


## Useful operations

In [28]:
# Transpose

t = torch.rand(size = (3, 5))
t_tr = t.T

print(t)
print(t_tr)

# another way to transpose for tensors of higher dimensions

# torch.transpose(tensor, dim0, dim1)
# swaps dim0 and dim1 of tensor
t_tr1 = torch.transpose(t, 0, 1)
print(t_tr1)

tensor([[0.8511, 0.9347, 0.3581, 0.6223, 0.2169],
        [0.6980, 0.3324, 0.5106, 0.4748, 0.5905],
        [0.6428, 0.1917, 0.8368, 0.5123, 0.4926]])
tensor([[0.8511, 0.6980, 0.6428],
        [0.9347, 0.3324, 0.1917],
        [0.3581, 0.5106, 0.8368],
        [0.6223, 0.4748, 0.5123],
        [0.2169, 0.5905, 0.4926]])
tensor([[0.8511, 0.6980, 0.6428],
        [0.9347, 0.3324, 0.1917],
        [0.3581, 0.5106, 0.8368],
        [0.6223, 0.4748, 0.5123],
        [0.2169, 0.5905, 0.4926]])


In [31]:
t = torch.zeros(30)
t_reshape = t.reshape(5, 6)
print(f"{t.shape} --> {t_reshape.shape}")

torch.Size([30]) --> torch.Size([5, 6])


In [42]:
# to remove unwanted dims whose dims = 1
t = torch.zeros(size = (1, 5, 7, 1, 3, 4))
print(t.shape)

# this removes all dims of size 1
t_sqz = t.squeeze() 
print(t_sqz.shape)

# this tells which dim to squeeze
# in this case, this squeezes dim 0
# if u do torch.squeeze(t, 2)
# nothing happens since the second dim has size 7
t_sqz1 = torch.squeeze(t, 0) 
print(t_sqz1.shape)

t_sqz2 = torch.squeeze(t, 2)
print(t_sqz2.shape)

torch.Size([1, 5, 7, 1, 3, 4])
torch.Size([5, 7, 3, 4])
torch.Size([5, 7, 1, 3, 4])
torch.Size([1, 5, 7, 1, 3, 4])


In [40]:
t_sqz1.shape

torch.Size([5, 7, 1, 3, 4])