In [1]:
import os
%run '/workspace/alvin/Machine_Learning_Studying/Yu_Xian/affine.py'
# from osgeo import gdal

In [2]:
rng = np.random.default_rng(999)

In [3]:
# gcps = []
px = rng.uniform(0, 799, size = 4)
py = rng.uniform(0, 599, size = 4)

X = rng.uniform(-180, 180, size = 4)
Y = rng.uniform(-90, 90, size = 4)
gcps_lst = list(zip(X, Y, px, py))
    
    # gcp = gdal.GCP(X, Y, 0, px, py)
    # gcps.append(gcp)

In [4]:
gcps_lst

[(np.float64(147.93952308870604),
  np.float64(2.327283624665725),
  np.float64(622.2811890466377),
  np.float64(102.49433703793743)),
 (np.float64(-111.3216218784706),
  np.float64(24.891853741700032),
  np.float64(137.6266560291843),
  np.float64(540.2528119295063)),
 (np.float64(20.6639647327448),
  np.float64(-3.1556200738362463),
  np.float64(570.1446619661385),
  np.float64(84.92714352482984)),
 (np.float64(40.34292524539279),
  np.float64(-38.01492663503724),
  np.float64(599.5177271454444),
  np.float64(366.1259940916348))]

In [ ]:
for i, gcp in enumerate(gcps):
    print(f"GCP {i}:")
    print(f"  pixel,line = ({gcp.GCPPixel}, {gcp.GCPLine})")
    print(f"  X,Y,Z      = ({gcp.GCPX}, {gcp.GCPY}, {gcp.GCPZ})")

In [ ]:
gt = gdal.GCPsToGeoTransform(gcps)

In [ ]:
gt

In [ ]:
res_lst = []
for (X, Y, px, py) in gcps_lst:
    pred_X, pred_Y = transform( (px, py), gt[0:3], gt[3:] )
    res_x = (pred_X - X)**2
    res_y = (pred_Y - Y)**2
    res = np.sqrt(res_x + res_y)
    print( (X, Y, px, py) )
    print(pred_X, pred_Y)
    res_lst.append(res)

In [ ]:
res_lst

In [7]:
gcps_lst_cp, E12, N12, E21, N21 = py_GCPTransformer(gcps_lst, False, -1, 3)

In [8]:
print(f"{gcps_lst}\n")
print(f"{E12}\n")
print(f"{N12}")

[(np.float64(147.93952308870604), np.float64(2.327283624665725), np.float64(622.2811890466377), np.float64(102.49433703793743)), (np.float64(-111.3216218784706), np.float64(24.891853741700032), np.float64(137.6266560291843), np.float64(540.2528119295063)), (np.float64(20.6639647327448), np.float64(-3.1556200738362463), np.float64(570.1446619661385), np.float64(84.92714352482984)), (np.float64(40.34292524539279), np.float64(-38.01492663503724), np.float64(599.5177271454444), np.float64(366.1259940916348))]

[-1.09124355e+02  3.33882701e-01 -1.00683745e-01]

[116.42569812  -0.17712195  -0.12606045]


In [9]:
py_res_lst = []
for (X, Y, px, py) in gcps_lst_cp:
    pred_X, pred_Y = transform( (px, py), E12, N12 )
    res_x = (pred_X - X)**2
    res_y = (pred_Y - Y)**2
    res = np.sqrt(res_x + res_y)
    # print( (X, Y, px, py) )
    print(pred_X, pred_Y)
    py_res_lst.append(res)
py_res_lst
# correct

88.32505516492675 -6.714443421892078
-117.56787199841146 23.94448491302508
72.68630151267544 4.734608353424695
54.18130650918238 -35.91605918706532


[np.float64(60.29624875412868),
 np.float64(6.317685356078305),
 np.float64(52.617290206536495),
 np.float64(13.99664390367058)]

In [10]:
transform( (400, 200), E12, N12)

(np.float64(4.291976084393937), np.float64(20.36482743679551))

# Testing Refine

In [11]:
gcps_lst_cp, E12, N12, E21, N21 = py_GCPTransformer(gcps_lst, True, -1, 3)

In [12]:
print(f"{gcps_lst_cp}\n")
print(f"{E12}\n")
print(f"{N12}")

[(np.float64(-111.3216218784706), np.float64(24.891853741700032), np.float64(137.6266560291843), np.float64(540.2528119295063)), (np.float64(20.6639647327448), np.float64(-3.1556200738362463), np.float64(570.1446619661385), np.float64(84.92714352482984)), (np.float64(40.34292524539279), np.float64(-38.01492663503724), np.float64(599.5177271454444), np.float64(366.1259940916348))]

[-1.76841056e+02  3.41298191e-01  3.43315290e-02]

[ 1.06155105e+02 -1.75997246e-01 -1.05582679e-01]


In [13]:
py_res_lst = []
for (X, Y, px, py) in gcps_lst:
    pred_X, pred_Y = transform( (px, py), E12, N12 )
    res_x = (pred_X - X)**2
    res_y = (pred_Y - Y)**2
    res = np.sqrt(res_x + res_y)
    # print( (X, Y, px, py) )
    print(pred_X, pred_Y)
    py_res_lst.append(res)
py_res_lst
# correct

39.061175726091165 -14.186296591998143
-111.32162187847064 24.89185374170011
20.663964732744656 -3.155620073836154
40.34292524539269 -38.014926635037156


[np.float64(110.12353452367218),
 np.float64(8.903074960742904e-14),
 np.float64(1.7248049877506383e-13),
 np.float64(1.3101760682293512e-13)]

In [14]:
transform( (400, 200), E12, N12)

(np.float64(-33.45547349715949), np.float64(14.639671317705762))

In [15]:
gcps_lst_cp, E12, N12, E21, N21 = py_GCPTransformer(gcps_lst, True, -1, 4)

In [16]:
print(f"{gcps_lst_cp}\n")
print(f"{E12}\n")
print(f"{N12}")

[(np.float64(147.93952308870604), np.float64(2.327283624665725), np.float64(622.2811890466377), np.float64(102.49433703793743)), (np.float64(-111.3216218784706), np.float64(24.891853741700032), np.float64(137.6266560291843), np.float64(540.2528119295063)), (np.float64(20.6639647327448), np.float64(-3.1556200738362463), np.float64(570.1446619661385), np.float64(84.92714352482984)), (np.float64(40.34292524539279), np.float64(-38.01492663503724), np.float64(599.5177271454444), np.float64(366.1259940916348))]

[-1.09124355e+02  3.33882701e-01 -1.00683745e-01]

[116.42569812  -0.17712195  -0.12606045]


In [17]:
py_res_lst = []
for (X, Y, px, py) in gcps_lst:
    pred_X, pred_Y = transform( (px, py), E12, N12 )
    res_x = (pred_X - X)**2
    res_y = (pred_Y - Y)**2
    res = np.sqrt(res_x + res_y)
    # print( (X, Y, px, py) )
    print(pred_X, pred_Y)
    py_res_lst.append(res)
py_res_lst
# correct

88.32505516492675 -6.714443421892078
-117.56787199841146 23.94448491302508
72.68630151267544 4.734608353424695
54.18130650918238 -35.91605918706532


[np.float64(60.29624875412868),
 np.float64(6.317685356078305),
 np.float64(52.617290206536495),
 np.float64(13.99664390367058)]